config/routes.rb
Rails.application.routes.draw do
  resources :memberships
  resources :beer_clubs
  resources :users do
    post 'toggle_activity', on: :member
  end
  resources :beers
  resources :places, only: [:index, :show]
  resources :ratings, only: [:index, :new, :create, :destroy]
  resource :session, only: [:new, :create, :destroy]
  resources :styles
  resources :breweries do
    post 'toggle_activity', on: :member
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/', to: 'breweries#index'
  get 'signup', to: 'users#new'
  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'
  post 'places', to: 'places#search'

  get 'beerlist', to:'beers#list'
  get 'brewerylist', to:'breweries#list'

  get 'auth/:provider/callback', to: 'sessions#create_oauth'
  post 'auth/github', to: 'sessions#gitbutton'
  root 'breweries#index'
  
end

app/models/beer_club.rb
class BeerClub < ApplicationRecord
  has_many :memberships
  has_many :members, through: :memberships, source: :user
end

app/controllers/beer_clubs_controller.rb
class BeerClubsController < ApplicationController
  before_action :ensure_that_signed_in, except: [:index, :show]
  before_action :set_beer_club, only: [:show, :edit, :update, :destroy]

  # GET /beer_clubs
  # GET /beer_clubs.json
  def index
    @beer_clubs = BeerClub.all

    order = params[:order] || 'name'

    @beer_clubs = case order
      when 'name' then @beer_clubs.sort_by{ |b| b.name }
      when 'founded' then @beer_clubs.sort_by{ |b| b.founded }
      when 'city' then @beer_clubs.sort_by{ |b| b.city }
    end
  end

  # GET /beer_clubs/1
  # GET /beer_clubs/1.json
  def show
    @membership = Membership.new
    @membership.user = current_user
    @membership.beer_club_id = params[:id]
  end

  # GET /beer_clubs/new
  def new
    @beer_club = BeerClub.new
  end

  # GET /beer_clubs/1/edit
  def edit
  end

  # POST /beer_clubs
  # POST /beer_clubs.json
  def create
    @beer_club = BeerClub.new(beer_club_params)

    respond_to do |format|
      if @beer_club.save
        format.html { redirect_to @beer_club, notice: 'Beer club was successfully created.' }
        format.json { render :show, status: :created, location: @beer_club }
      else
        format.html { render :new,  notice: 'Name cant be empty' }
        format.json { render json: @beer_club.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /beer_clubs/1
  # PATCH/PUT /beer_clubs/1.json
  def update
    respond_to do |format|
      if @beer_club.update(beer_club_params)
        format.html { redirect_to @beer_club, notice: 'Beer club was successfully updated.' }
        format.json { render :show, status: :ok, location: @beer_club }
      else
        format.html { render :edit }
        format.json { render json: @beer_club.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /beer_clubs/1
  # DELETE /beer_clubs/1.json
  def destroy
    @beer_club.destroy
    respond_to do |format|
      format.html { redirect_to beer_clubs_url, notice: 'Beer club was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_beer_club
    @beer_club = BeerClub.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def beer_club_params
    params.require(:beer_club).permit(:name, :founded, :city)
  end
end

app/helpers/beer_clubs_helper.rb
module BeerClubsHelper
end

app/views/beer_clubs/_form.html.erb
<%= form_with(model: beer_club, local: true) do |form| %>
  <% if beer_club.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(beer_club.errors.count, "error") %> prohibited this beer_club from being saved:</h2>

      <ul>
      <% beer_club.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :founded %>
    <%= form.number_field :founded, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city, class: "form-control" %>
  </div>

  <div class="actions">
     <%= form.submit class:"btn btn-primary" %>
  </div>
<% end %>

app/views/beer_clubs/edit.html.erb
<h1>Editing Beer Club</h1>

<%= render 'form', beer_club: @beer_club %>

<%= link_to 'Show', @beer_club %> |
<%= link_to 'Back', beer_clubs_path %>

app/views/beer_clubs/index.html.erb
<p id="notice"></p>

<h1>Beer Clubs</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th><%= link_to 'Name', beer_clubs_path(order:"name") %></th>
      <th><%= link_to 'Founded', beer_clubs_path(order:"founded") %></th>
      <th><%= link_to 'City', beer_clubs_path(order:"city") %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @beer_clubs.each do |beer_club| %>
      <tr>
        <td><%= link_to beer_club.name, beer_club %></td>
        <td><%= beer_club.founded %></td>
        <td><%= beer_club.city %></td>
        <td><%= link_to 'Show', beer_club  if current_user%></td>
        <td><%= link_to 'Edit', edit_beer_club_path(beer_club) if current_user%></td>
        <td><%= link_to 'Destroy', beer_club, method: :delete, data: { confirm: 'Are you sure?' }  if current_user%></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Beer Club', new_beer_club_path if current_user %>

app/views/beer_clubs/new.html.erb
<h1>New Beer Club</h1>

<%= render 'form', beer_club: @beer_club %>

<%= link_to 'Back', beer_clubs_path %>

app/views/beer_clubs/show.html.erb
<p id="notice"></p>

<h2>
  <%= @beer_club.name %> <%= @beer_club.city %>
</h2>
<% if current_user %>
  <% if @beer_club.memberships.select{|m| m.user_id == @membership.user_id}.size < 1 %>
  <%= form_for(@membership) do |f| %>
  <%= f.hidden_field :beer_club_id %>
  <%= f.submit value:"join the club" %>
  <% end %>
  <% else %>
  <%= form_for(@membership, url: membership_path(@beer_club.memberships.select{|m| m.user_id == @membership.user_id}[0].id), method: "delete") do |f| %>
  <%= f.hidden_field :beer_club_id %>
  <%= f.submit value: "end the membership" %>
  <% end %>
  <% end %>
<% end %>
<p>
 Founded
  <%= @beer_club.founded %>
</p>

<h3>Members</h3>

<ul>
  <% @beer_club.members.each do |member| %>
    <li><%= link_to member.username, member %></li>
  <% end %>
</ul>

<%= link_to 'Edit', edit_beer_club_path(@beer_club) %> 