config/routes.rb
Rails.application.routes.draw do
  resources :memberships
  resources :beer_clubs
  resources :users do
    post 'toggle_activity', on: :member
  end
  resources :beers
  resources :places, only: [:index, :show]
  resources :ratings, only: [:index, :new, :create, :destroy]
  resource :session, only: [:new, :create, :destroy]
  resources :styles
  resources :breweries do
    post 'toggle_activity', on: :member
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/', to: 'breweries#index'
  get 'signup', to: 'users#new'
  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'
  post 'places', to: 'places#search'

  get 'beerlist', to:'beers#list'
  get 'brewerylist', to:'breweries#list'

  get 'auth/:provider/callback', to: 'sessions#create_oauth'
  post 'auth/github', to: 'sessions#gitbutton'
  root 'breweries#index'
  
end

app/models/user.rb
class User < ApplicationRecord
  has_many :ratings, dependent: :destroy
  has_many :beers, through: :ratings
  has_many :memberships, dependent: :destroy
  has_many :beer_clubs, through: :memberships

  include RatingAverage

  has_secure_password

  validates :username, uniqueness: true,
                       length: { minimum: 3 }

  validates :password, length: { minimum: 4 },
                       format: {
                         with: /[A-Z].*\d|\d.*[A-Z]/,
                         message: "must contain one capital letter and number"
                       }

  def favorite_beer
    return nil if ratings.empty?

    ratings.max_by(&:score).beer
  end

  def favorite_style
    return nil if ratings.empty?

    thestyle = ''
    theaverage = 0

    ratings.map{ |rating| rating.beer.style.name }.uniq.each do |style|
      scores = ratings.select{ |rating| rating.beer.style.name == style }.map(&:score)
      average = scores.reduce(:+) / scores.size.to_f
      if average >= theaverage
        theaverage = average
        thestyle = style
      end
    end
    thestyle
  end

  def favorite_brewery
    return nil if ratings.empty?

    thebrewery = ''
    theaverage = 0

    ratings.map{ |rating| rating.beer.brewery }.uniq.each do |brewery|
      scores = ratings.select{ |rating| rating.beer.brewery == brewery }.map(&:score)
      average = scores.reduce(:+) / scores.size.to_f
      if average >= theaverage
        theaverage = average
        thebrewery = brewery
      end
    end
    thebrewery.name
  end

  def self.top(n)
    sorted_by_rating_in_desc_order = User.all.sort_by{ |b| -(b.average_rating || 0) }
    sorted_by_rating_in_desc_order.take(n)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_that_admin, only: [:toggle_activity]
  before_action :ensure_that_signed_in, except: [:index, :show, :new, :create]
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.includes(:ratings, :beers).all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if user_params[:username].nil? && (@user == current_user) && @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    return unless current_user == @user

    Rating.where(user: current_user).destroy_all
    reset_session
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def toggle_activity
    user = User.find(params[:id])
    if user.id != current_user.id
      user.update_attribute :closed, !user.closed

      new_status = user.closed? ? "closed" : "opened"

      redirect_to user, notice: "user account #{new_status}"
    else
      redirect_to users_url, notice: "cant change your own status"
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:username, :password, :password_confirmation)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<% if @user.new_record? %>
  <div class="field">
  <%= form.label :username %>
  <%= form.text_field :username %>
  </div>
<% end %>

  <div class="field">
  <%= form.label :password %><br />
  <%= form.password_field :password %>
</div>

<div class="field">
  <%= form.label :password_confirmation %><br />
  <%= form.password_field :password_confirmation  %>
</div>

  <div class="actions">
  <% if @user.new_record? %>
     <%= form.submit class:"btn btn-primary" %>
  <% else %>
    <%= form.submit 'Update password' %>
  <% end %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"></p>

<h1>Users</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Username</th>
      <th> rated beers </th>
      <th> total ratings </th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.username, user %></td>
        <td><%= user.beers.size %></td>
        <td><%= user.ratings.size %></td>
        <td><%= link_to "Change account status", toggle_activity_user_path(user.id), method: :post, class: "btn btn-primary" if current_user && current_user.admin && current_user.id != user.id %></td>
        <%  if user.closed && current_user && current_user.admin %>
         <td style='color:red'>Closed</td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>
<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"></p>
<% if  @user.closed %>
<div class="alert alert-danger" role="alert">
  Account is closed
  <%= link_to "Open account", toggle_activity_user_path(@user.id), method: :post, class: "btn btn-outline-success" if current_user && current_user.admin && current_user.id != @user.id %>
</div>
<%end%>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
  <td><%= link_to 'Destroy', @user, method: :delete, data: { confirm: 'Are you sure?' } %></td>

</p>

<% if  @user.ratings.length() > 0%>
Has made <%= @user.ratings.length() %>, avarage rating <%= @user.average_rating().truncate(2)%>
<p>Favorite style = <%= @user.favorite_style() %></p>
<p>Favorite brewery = <%= @user.favorite_brewery() %></p>
<% end %>
<p>
  <% if @user.beer_clubs.any? %>
    member of 
    <% @user.beer_clubs.each do |club| %>
      <li> <%= link_to club.name, club %> </li>
    <% end %>
  <% end %>
</p>

<h3>ratings</h3>

<ul>
 <% @user.ratings.each do |rating| %>
 <li> <%= rating.beer.name %>, <%= rating.score %>,
 <% if @user == current_user %>
  <%= link_to 'Destroy', rating, method: :delete, data: { confirm: 'Are you sure?' }, id: rating.id%></li>
 <% end %>
 <% end %>
 <ul>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>