config/routes.rb
Rails.application.routes.draw do
  resources :memberships
  resources :beer_clubs
  resources :users do
    post 'toggle_activity', on: :member
  end
  resources :beers
  resources :places, only: [:index, :show]
  resources :ratings, only: [:index, :new, :create, :destroy]
  resource :session, only: [:new, :create, :destroy]
  resources :styles
  resources :breweries do
    post 'toggle_activity', on: :member
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/', to: 'breweries#index'
  get 'signup', to: 'users#new'
  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'
  post 'places', to: 'places#search'

  get 'beerlist', to:'beers#list'
  get 'brewerylist', to:'breweries#list'

  get 'auth/:provider/callback', to: 'sessions#create_oauth'
  post 'auth/github', to: 'sessions#gitbutton'
  root 'breweries#index'
  
end

app/models/brewery.rb
class Brewery < ApplicationRecord
  include RatingAverage

  validates :name, presence: true
  validates :year, numericality: { only_integer: true,
                                   greater_than: 1039,
                                   less_than_or_equal_to: ->(_) { Time.now.year } }

  has_many :beers, dependent: :destroy
  has_many :ratings, through: :beers

  scope :active, -> { where active: true }
  scope :retired, -> { where active: [nil, false] }

  def print_report
    puts name
    puts "established at year #{year}"
    puts "number of beers #{beers.count}"
  end

  def restart
    self.year = 2018
    puts "changed year to #{year}"
  end

  def self.top(n)
    sorted_by_rating_in_desc_order = Brewery.all.sort_by{ |b| -(b.average_rating || 0) }
    sorted_by_rating_in_desc_order.take(n)
  end
end

app/controllers/breweries_controller.rb
class BreweriesController < ApplicationController
  before_action :ensure_that_admin, only: [:destroy]
  before_action :ensure_that_signed_in, except: [:index, :show, :list]
  before_action :set_brewery, only: [:show, :edit, :update, :destroy]

  # GET /breweries
  # GET /breweries.json
  def index
    @active_breweries = Brewery.active
    @retired_breweries = Brewery.retired
    @breweries = Brewery.all

  end

  # GET /breweries/1
  # GET /breweries/1.json
  def show
  end

  # GET /breweries/new
  def new
    expire_fragment('brewerylist')
    @brewery = Brewery.new
  end

  # GET /breweries/1/edit
  def edit
  end

  # POST /breweries
  # POST /breweries.json
  def create
    expire_fragment('brewerylist')
    puts 'halooo'
    puts brewery_params
    @brewery = Brewery.new(brewery_params)

    respond_to do |format|
      if @brewery.save
        format.html { redirect_to @brewery, notice: 'Brewery was successfully created.' }
        format.json { render :show, status: :created, location: @brewery }
      else
        format.html { render :new }
        format.json { render json: @brewery.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /breweries/1
  # PATCH/PUT /breweries/1.json
  def update
    expire_fragment('brewerylist')
    respond_to do |format|
      if @brewery.update(brewery_params)
        format.html { redirect_to @brewery, notice: 'Brewery was successfully updated.' }
        format.json { render :show, status: :ok, location: @brewery }
      else
        format.html { render :edit }
        format.json { render json: @brewery.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /breweries/1
  # DELETE /breweries/1.json
  def destroy
    @brewery.destroy
    respond_to do |format|
      format.html { redirect_to breweries_url, notice: 'Brewery was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def toggle_activity
    brewery = Brewery.find(params[:id])
    brewery.update_attribute :active, !brewery.active

    new_status = brewery.active? ? "active" : "retired"

    redirect_to brewery, notice: "brewery activity status changed to #{new_status}"
  end

  def list
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_brewery
    @brewery = Brewery.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def brewery_params
    params.require(:brewery).permit(:name, :year, :active)
  end

  # def authenticate
  #   admin_accounts = { "pekka" => "beer", "arto" => "foobar", "matti" => "ittam", "vilma" => "kAngas" }
  #   authenticate_or_request_with_http_basic do |username, password|
  #     login_ok = if admin_accounts[username.downcase].casecmp(password).zero?
  #                  true
  #                else
  #                  false # käyttäjätunnus/salasana oli väärä
  #                end

  #     # koodilohkon arvo on sen viimeisen komennon arvo eli true/false riippuen kirjautumisen onnistumisesta
  #     login_ok
  #   end
  # end
end

app/helpers/breweries_helper.rb
module BreweriesHelper
end

app/views/breweries/_form.html.erb
<%= form_with(model: brewery, local: true) do |form| %>
  <% if brewery.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(brewery.errors.count, "error") %> prohibited this brewery from being saved:</h2>
      <ul>
        <% brewery.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <div class="field">
    <%= form.label :year %>
    <%= form.number_field :year %>
  </div>
  <div class="field">
    <%= form.label :active %>
    <%= form.check_box :active %>
  </div>
  <div class="actions">
    <%= form.submit class:"btn btn-primary" %>
  </div>
<% end %>

app/views/breweries/_list.html.erb
  <table class="table table-hover">
    <thead>
      <tr>
        <th>Name</th>
        <th>Year</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% breweries.each do |brewery| %>
        <tr>
          <td><%= link_to brewery.name, brewery %></td>
          <td><%= brewery.year %></td>
          <td><%= link_to('Destroy', brewery, method: :delete, data: { confirm: 'Are you sure?' }, class:'btn btn-danger', style:'color:white')  if current_user && current_user.admin? %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

app/views/breweries/edit.html.erb
<h1>Editing Brewery</h1>

<%= render 'form', brewery: @brewery %>

<%= link_to 'Show', @brewery %> |
<%= link_to 'Back', breweries_path %>

app/views/breweries/index.html.erb
<h1>Breweries</h1>
  <h2>Active</h2>
  <p> Number of active breweries: <%= @active_breweries.count %> </p>
  <%= render 'list', breweries: @active_breweries %>
  <h2>Retired</h2>
  <p> Number of retired breweries: <%= @retired_breweries.count %> </p>
  <%= render 'list', breweries: @retired_breweries %>
<br>
<%= link_to 'New Brewery', new_brewery_path, class:"btn btn-primary"  %>

app/views/breweries/list.html.erb
<h2>Breweries</h2>
<table id="brewerytable" class="table table-hover">
  <tr>
    <th> <a href="#" id="name">Name</a> </th>
    <th> <a href="#" id="year">Year</a> </th>
    <th> <a href="#" id="beers">Beers</a> </th>
  </tr>

</table>

app/views/breweries/new.html.erb
<h1>New Brewery</h1>

<%= render 'form', brewery: @brewery %>

<%= link_to 'Back', breweries_path %>

app/views/breweries/show.html.erb
<p id="notice"></p>

<p>
  <strong>Name:</strong>
  <%= @brewery.name %>
   <% if not @brewery.active  %>
    <span class="badge badge-info">retired</span>
  <% end %>
</p>

<p>
  Established at
  <%= @brewery.year %>
</p>

<p>
  <strong>Beers</strong>
 
  (Number of beers: <%= @brewery.beers.count %>)
  <% @brewery.beers.each do |beer| %>
    <br/>
    <%= link_to beer.name, beer %>
  <% end %>
  <br/>
 
</p>

<p>
  Has <%= pluralize(@brewery.ratings.length, 'rating') %> <br/>
   <% if  @brewery.average_rating() %>
    Avarage: <%= @brewery.average_rating().truncate(2) %>
  <% end %>
  
</p>
<%= link_to "change activity", toggle_activity_brewery_path(@brewery.id), method: :post, class: "btn btn-primary" %>
<br/>
<br/>
<%= link_to 'Edit', edit_brewery_path(@brewery)  if current_user%> |
<%= link_to 'Back', breweries_path %>